# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EH_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EH1', models.CharField(max_length=200)),
                ('EH2', models.CharField(max_length=200)),
                ('EH3', models.CharField(max_length=200)),
                ('EH4', models.CharField(max_length=200)),
                ('EH5', models.CharField(max_length=200)),
                ('EH6', models.CharField(max_length=200)),
                ('EH7', models.CharField(max_length=200)),
                ('EH8', models.CharField(max_length=200)),
                ('EH9', models.CharField(max_length=200)),
                ('EH10', models.CharField(max_length=200)),
                ('EH11', models.CharField(max_length=200)),
                ('EH12', models.CharField(max_length=200)),
                ('EH13', models.CharField(max_length=200)),
                ('EH14', models.CharField(max_length=200)),
                ('EH15', models.CharField(max_length=200)),
                ('EH16', models.CharField(max_length=200)),
                ('EH17', models.CharField(max_length=200)),
                ('EH18', models.CharField(max_length=200)),
                ('EH19', models.CharField(max_length=200)),
                ('EH20', models.CharField(max_length=200)),
                ('EH21', models.CharField(max_length=200)),
                ('EH22', models.CharField(max_length=200)),
                ('EH23', models.CharField(max_length=200)),
                ('EH24', models.CharField(max_length=200)),
            ],
        ),
    ]
