# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0004_tip_tip_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='TIP1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP10',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP11',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP12',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP13',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP14',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP15',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP2',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP3',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP4',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP5',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP6',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP7',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP8',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
        migrations.AlterField(
            model_name='tip',
            name='TIP9',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=None),
        ),
    ]
