# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0005_auto_20170726_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='es_question',
            old_name='EH1',
            new_name='ES1',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH10',
            new_name='ES10',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH11',
            new_name='ES11',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH12',
            new_name='ES12',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH13',
            new_name='ES13',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH14',
            new_name='ES14',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH15',
            new_name='ES15',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH2',
            new_name='ES2',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH3',
            new_name='ES3',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH4',
            new_name='ES4',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH5',
            new_name='ES5',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH6',
            new_name='ES6',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH7',
            new_name='ES7',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH8',
            new_name='ES8',
        ),
        migrations.RenameField(
            model_name='es_question',
            old_name='EH9',
            new_name='ES9',
        ),
    ]
