# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0007_auto_20170726_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spr_question',
            name='SPR7',
        ),
        migrations.RemoveField(
            model_name='spr_question',
            name='SPR8',
        ),
    ]
