# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0009_eb_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EB_Question',
        ),
    ]
