# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0010_delete_eb_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='EB_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EB1', models.CharField(max_length=200)),
                ('EB2', models.CharField(max_length=200)),
                ('EB3', models.CharField(max_length=200)),
                ('EB4', models.CharField(max_length=200)),
                ('EB5', models.CharField(max_length=200)),
                ('EB6', models.CharField(max_length=200)),
                ('EB7', models.CharField(max_length=200)),
                ('EB8', models.CharField(max_length=200)),
                ('EB9', models.CharField(max_length=200)),
                ('EB10', models.CharField(max_length=200)),
                ('EB11', models.CharField(max_length=200)),
                ('EB12', models.CharField(max_length=200)),
                ('EB13', models.CharField(max_length=200)),
                ('EB14', models.CharField(max_length=200)),
                ('EB15', models.CharField(max_length=200)),
                ('EB16', models.CharField(max_length=200)),
                ('EB17', models.CharField(max_length=200)),
                ('EB18', models.CharField(max_length=200)),
                ('EB19', models.CharField(max_length=200)),
                ('EB20', models.CharField(max_length=200)),
                ('EB21', models.CharField(max_length=200)),
                ('EB22', models.CharField(max_length=200)),
                ('EB23', models.CharField(max_length=200)),
                ('EB24', models.CharField(max_length=200)),
                ('EB25', models.CharField(max_length=200)),
                ('EB26', models.CharField(max_length=200)),
                ('EB27', models.CharField(max_length=200)),
            ],
        ),
    ]
