# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0012_eb_surveytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eb',
            name='surveytime',
        ),
    ]
