# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0013_remove_eb_surveytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='eb',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
    ]
