# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0014_eb_surveytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='eh',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='es',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exf',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='f',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gd',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gr',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hm',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='r',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sef',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spr',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssp',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='surveytime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PSS.SurveyTimes'),
            preserve_default=False,
        ),
    ]
