# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0015_auto_20170727_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eh',
            name='surveytime',
            field=models.IntegerField(),
        ),
    ]
