# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0019_auto_20170802_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='DM1',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], default=None),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM10',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM13',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM1_3',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], default=0),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM1_4',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], default=0),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM2',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], default=0),
        ),
    ]
