# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0020_auto_20170802_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eb',
            name='surveytime',
            field=models.IntegerField(),
        ),
    ]
