# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0022_total_for_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_for_admin',
            name='Agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
