# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0023_auto_20170803_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_for_admin',
            name='GR_Con',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
