# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0026_total_for_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_for_admin',
            name='Agent',
        ),
        migrations.RemoveField(
            model_name='total_for_admin',
            name='caseNum',
        ),
        migrations.DeleteModel(
            name='Total_for_Admin',
        ),
    ]
