# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PSS', '0027_auto_20170804_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_for_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.IntegerField()),
                ('Date', models.DateField()),
                ('Health', models.FloatField()),
                ('Community', models.FloatField()),
                ('Childcare', models.FloatField()),
                ('Jobskills', models.FloatField()),
                ('SoftSkill', models.FloatField()),
                ('Peb_all', models.FloatField()),
                ('Empowerment', models.FloatField()),
                ('Selfmotivation', models.FloatField()),
                ('SkilResources', models.FloatField()),
                ('GaolOrientation', models.FloatField()),
                ('Ehs_all', models.FloatField()),
                ('Ess1', models.FloatField()),
                ('Ess2', models.FloatField()),
                ('Ess3', models.FloatField()),
                ('Ess4', models.FloatField()),
                ('Ess_all', models.FloatField()),
                ('PSS', models.FloatField()),
                ('Resilience', models.FloatField()),
                ('Self_Efficacy', models.FloatField()),
                ('GR_Con', models.FloatField()),
                ('GR_Per', models.FloatField()),
                ('GR_all', models.FloatField()),
                ('SPR_all', models.FloatField()),
                ('F_self', models.FloatField()),
                ('F_other', models.FloatField()),
                ('F_situation', models.FloatField()),
                ('F_all', models.FloatField()),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('caseNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PSS.Surveyee')),
            ],
        ),
    ]
