# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0029_auto_20170816_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytimes',
            name='doneSurvey',
            field=models.BooleanField(default=False),
        ),
    ]
