# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0032_auto_20170902_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytimes',
            name='readyToStart',
            field=models.BooleanField(default=False),
        ),
    ]
