# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0033_surveytimes_readytostart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='DM1',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=None),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM10',
            field=models.IntegerField(choices=[(1, 1), (0, 0)]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM11_1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM11_2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM11_3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM11_4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM13',
            field=models.IntegerField(choices=[(1, 1), (0, 0)]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM14',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM16',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM1_3',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM1_4',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM2',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=0),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM8',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='dm',
            name='DM9',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='total_for_admin',
            name='DM11_1',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='total_for_admin',
            name='DM11_2',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='total_for_admin',
            name='DM11_3',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='total_for_admin',
            name='DM11_4',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='total_for_admin',
            name='DM14',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
        migrations.AlterField(
            model_name='total_for_admin',
            name='DM16',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
        migrations.AlterField(
            model_name='total_for_admin',
            name='DM8',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='total_for_admin',
            name='DM9',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
