# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0035_auto_20170906_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyee',
            name='survey_kind',
            field=models.IntegerField(default=1),
        ),
    ]
