# Generated by Django 2.0.1 on 2018-01-02 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0036_surveyee_survey_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_for_admin',
            name='Agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
