# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0039_surveytimes_onilne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveytimes',
            name='onilne',
        ),
        migrations.AddField(
            model_name='surveytimes',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
