# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0040_auto_20180122_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exf',
            old_name='A3',
            new_name='A_3',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='B3',
            new_name='B_3',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='C3',
            new_name='C_3',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='D3',
            new_name='D_3',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='E2',
            new_name='E_2',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='F2',
            new_name='F_2',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='G1',
            new_name='G_1',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='H3',
            new_name='H_3',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='I2',
            new_name='I_2',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='J3',
            new_name='J_3',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='K1',
            new_name='K_1',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='K2',
            new_name='K_2',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='K3',
            new_name='K_3',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='L1',
            new_name='L_1',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='L2',
            new_name='L_2',
        ),
        migrations.RenameField(
            model_name='exf',
            old_name='L3',
            new_name='L_3',
        ),
    ]
