# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0041_auto_20180124_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytimes',
            name='pub_Date',
            field=models.DateField(),
        ),
    ]
