# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0042_auto_20180124_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyee',
            name='survey1',
        ),
        migrations.RemoveField(
            model_name='surveyee',
            name='survey2',
        ),
        migrations.RemoveField(
            model_name='surveyee',
            name='survey3',
        ),
        migrations.RemoveField(
            model_name='surveyee',
            name='survey4',
        ),
        migrations.RemoveField(
            model_name='surveyee',
            name='survey_kind',
        ),
    ]
