# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0043_auto_20180124_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyee',
            name='survey1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyee',
            name='survey2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyee',
            name='survey3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyee',
            name='survey4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyee',
            name='survey_kind',
            field=models.IntegerField(default=1),
        ),
    ]
