# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0046_auto_20180130_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyee',
            name='readyToStart',
            field=models.BooleanField(default=False),
        ),
    ]
