# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0048_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GENB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('surveytime', models.IntegerField()),
                ('GENB1', models.IntegerField(default=None)),
                ('GENB2', models.IntegerField(default=None)),
                ('GENB3', models.IntegerField(default=None)),
                ('GENB4', models.IntegerField(default=None)),
                ('caseNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PSS.Surveyee')),
            ],
        ),
        migrations.CreateModel(
            name='GENB_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GENB1', models.CharField(max_length=200)),
                ('GENB2', models.CharField(max_length=200)),
                ('GENB3', models.CharField(max_length=200)),
                ('GENB4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='K6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('surveytime', models.IntegerField()),
                ('Q1_a', models.IntegerField(default=None)),
                ('Q1_b', models.IntegerField(default=None)),
                ('Q1_c', models.IntegerField(default=None)),
                ('Q1_d', models.IntegerField(default=None)),
                ('Q1_e', models.IntegerField(default=None)),
                ('Q1_f', models.IntegerField(default=None)),
                ('Q2', models.IntegerField(default=None)),
                ('Q3', models.IntegerField(default=None)),
                ('Q4', models.IntegerField(default=None)),
                ('Q5', models.IntegerField(default=None)),
                ('Q6', models.IntegerField(default=None)),
                ('caseNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PSS.Surveyee')),
            ],
        ),
        migrations.CreateModel(
            name='K6_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1_a', models.CharField(max_length=200)),
                ('Q1_b', models.CharField(max_length=200)),
                ('Q1_c', models.CharField(max_length=200)),
                ('Q1_d', models.CharField(max_length=200)),
                ('Q1_e', models.CharField(max_length=200)),
                ('Q1_f', models.CharField(max_length=200)),
                ('Q2', models.CharField(max_length=200)),
                ('Q3', models.CharField(max_length=200)),
                ('Q4', models.CharField(max_length=200)),
                ('Q5', models.CharField(max_length=200)),
                ('Q6', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TIPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('surveytime', models.IntegerField()),
                ('TIPI1', models.IntegerField(default=None)),
                ('TIPI2', models.IntegerField(default=None)),
                ('TIPI3', models.IntegerField(default=None)),
                ('TIPI4', models.IntegerField(default=None)),
                ('TIPI5', models.IntegerField(default=None)),
                ('TIPI6', models.IntegerField(default=None)),
                ('TIPI7', models.IntegerField(default=None)),
                ('TIPI8', models.IntegerField(default=None)),
                ('TIPI9', models.IntegerField(default=None)),
                ('TIPI10', models.IntegerField(default=None)),
                ('caseNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PSS.Surveyee')),
            ],
        ),
        migrations.CreateModel(
            name='TIPI_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPI1', models.CharField(max_length=200)),
                ('TIPI2', models.CharField(max_length=200)),
                ('TIPI3', models.CharField(max_length=200)),
                ('TIPI4', models.CharField(max_length=200)),
                ('TIPI5', models.CharField(max_length=200)),
                ('TIPI6', models.CharField(max_length=200)),
                ('TIPI7', models.CharField(max_length=200)),
                ('TIPI8', models.CharField(max_length=200)),
                ('TIPI9', models.CharField(max_length=200)),
                ('TIPI10', models.CharField(max_length=200)),
            ],
        ),
    ]
