# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0050_auto_20180207_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k6_question',
            name='Q2',
            field=models.CharField(max_length=400),
        ),
    ]
