# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0051_auto_20180207_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='EB_Short_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EB1', models.CharField(max_length=200)),
                ('EB2', models.CharField(max_length=200)),
                ('EB3', models.CharField(max_length=200)),
                ('EB4', models.CharField(max_length=200)),
                ('EB5', models.CharField(max_length=200)),
                ('EB6', models.CharField(max_length=200)),
                ('EB7', models.CharField(max_length=200)),
                ('EB8', models.CharField(max_length=200)),
                ('EB9', models.CharField(max_length=200)),
                ('EB10', models.CharField(max_length=200)),
                ('EB11', models.CharField(max_length=200)),
                ('EB12', models.CharField(max_length=200)),
                ('EB13', models.CharField(max_length=200)),
                ('EB14', models.CharField(max_length=200)),
            ],
        ),
    ]
