# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0052_eb_short_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EB_Short_Question',
            new_name='EH_Short_Question',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB1',
            new_name='EH1',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB10',
            new_name='EH10',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB11',
            new_name='EH11',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB12',
            new_name='EH12',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB13',
            new_name='EH13',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB14',
            new_name='EH14',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB2',
            new_name='EH2',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB3',
            new_name='EH3',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB4',
            new_name='EH4',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB5',
            new_name='EH5',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB6',
            new_name='EH6',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB7',
            new_name='EH7',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB8',
            new_name='EH8',
        ),
        migrations.RenameField(
            model_name='eh_short_question',
            old_name='EB9',
            new_name='EH9',
        ),
    ]
