# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0053_auto_20180207_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
    ]
