# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0054_auto_20180311_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
